spring:
  application:
    name: scorex-backend
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb+srv://honphan:qzEgxNtlOv0LLNCT@cluster0.r8jf1uu.mongodb.net/scoreX

server:
  port: 8080