name: Backend Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # chạy mọi lệnh trong folder ./backend
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cài đặt Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'        
        distribution: 'temurin'
        cache: maven

    - name: Cấp quyền
      run: chmod +x mvnw

    - name: Chạy Test 
      run: ./mvnw clean test
